Repository CruGlobal/ab_platform_web, pull requests merged in 2023-09, with the labels that each got.

#374 Auto Version
  .github/workflows/dispatch-web-update.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/pr-merge-release.yml
  .github/workflows/update-core-version.yml
  .github/workflows/update-web-service.yml
  README.md
Labels: major

#376 fix remove invalid dependant job
  .github/workflows/pr-merge-release.yml
Labels: major

#377 fix remove invalid job dependency
  .github/workflows/dispatch-web-update.yml
Labels: major

#378 fix pass in token
  .github/workflows/dispatch-web-update.yml
  .github/workflows/pr-merge-release.yml
  .github/workflows/update-core-version.yml
Labels: skip-release

#380 Sentry Performance Tracking
  AppBuilder/platform/ABModel.js
  init/Bootstrap.js
  init/sentry.js
  package-lock.json
  package.json
  resources/NetworkRestSocket.js
  webpack.common.js
  webpack.config.js
  webpack.dev.js
  webpack.prod.js
Labels: patch

#383 Some Scheduler views are not displaying data
  AppBuilder/platform/views/viewComponent/ABViewComponent.js
  AppBuilder/platform/views/viewComponent/ABViewReportsManagerComponent.js
  AppBuilder/platform/views/viewComponent/ABViewSchedulerComponent.js
Labels: bug, patch

#382 cleanup old gzip and license files
  webpack.common.js
Labels: patch

#384 *Add filter to application menu list
  ui/portal_work.js
Labels: enhancement, minor
