Repository CruGlobal/ab_platform_web, pull requests merged in 2024-06, with the labels that each got.

#529 *Fix pull value of the record rule option
  AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
Labels: patch

#535 Insert images with proper proportions in DocX templates.
  AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
  package-lock.json
  package.json
  webpack.dev.js
  webpack.prod.js
Labels: bug, patch

#537 Use the related object and not just the UUID.
  AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
Labels: bug, patch

#514 Refactor our Socket Broadcasts to limit the number of updates we send out.
  AppBuilder/platform/dataFields/ABFieldConnect.js
  AppBuilder/platform/views/viewComponent/ABViewFormButtonComponent.js
  AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
  AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
  resources/Network.js
  resources/NetworkRestSocket.js
Labels: patch

#539 Support user filters in DocX reports.
  AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
Labels: enhancement, patch

#540 Upgrade data fetch to include latest features.
  AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
Labels: enhancement, patch

#527 upgrade pdfjs-dist
  AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js
  init/pdfjs.js
  package-lock.json
  package.json
  webpack.common.js
Labels: patch

#542 hotfix look at cursor set for current data collection
  AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
Labels: bug, patch

#543 Loop through result data to find images to download.
  AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
Labels: enhancement, patch

#544 Check if connection is on an indexed field and use index to filter re…
  AppBuilder/platform/views/viewComponent/ABViewDataFilterComponent.js
Labels: enhancement, patch
