Repository CruGlobal/ab_platform_web, pull requests merged in 2024-04, with the labels that each got.

#485 Adjust webix loading in parellel with init
  index.js
  init/Bootstrap.js
Labels: patch

#490 Some Temporary logs to help me gauge the impact of our socket communications.
  AppBuilder/platform/ABDataCollection.js
  resources/NetworkRestSocket.js
Labels: minor

#492 Eslint changes
  AppBuilder/platform/ABObject.js
  AppBuilder/platform/dataFields/ABFieldConnect.js
  AppBuilder/platform/dataFields/ABFieldString.js
  AppBuilder/platform/mobile/ABMobilePage.js
  AppBuilder/platform/mobile/ABMobileViewFormConnect.js
  AppBuilder/platform/views/ABViewChart.js
  AppBuilder/platform/views/ABViewGridPopupExport.js
  AppBuilder/platform/views/ABViewGridPopupMassUpdate.js
  AppBuilder/platform/views/ABViewKanbanFormSidePanel.js
  AppBuilder/platform/views/viewComponent/ABViewCSVImporterComponent.js
  AppBuilder/platform/views/viewComponent/ABViewChartLineComponent.js
  AppBuilder/platform/views/viewComponent/ABViewChartPieComponent.js
  AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js
  AppBuilder/platform/views/viewComponent/ABViewDetailItemComponent.js
  AppBuilder/platform/views/viewComponent/ABViewPivotComponent.js
  AppBuilder/platform/views/viewProperties/ABViewPropertyLinkPage.js
  AppBuilder/rules/ruleActions/ABViewRuleActionFormSubmitRuleEmail.js
  AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
  init/initAttach.js
  init/initConnectListerner.js
  resources/Network.js
  resources/NetworkRest.js
  ui/portal_access_level_manager.js
  ui/portal_auth_login_resetPassword.js
  ui/portal_tutorial_manager.js
  ui/portal_work.js
  ui/portal_work_user_qr_window.js
  webix_custom_components/activelist.js
  webix_custom_components/datetimepicker.js
  webix_custom_components/editlist.js
  webix_custom_components/edittree.js
  webix_custom_components/focusableTemplate.js
  webix_custom_components/numbertext.js
  webix_custom_components/savablelayout.js
  webix_custom_components/timepicker.js
  webix_custom_components/treesuggest.js
Labels: patch

#496 Fix: prevent undefined values from causing ABFieldUser.pullRelationValues() from crashing
  AppBuilder/platform/dataFields/ABFieldUser.js
  resources/NetworkRestSocket.js
Labels: patch

#497 +Add loading cursor to switcheroo to let users know the progress
  ui/portal_work.js
Labels: patch

#488 Fixes to CodeQL warnings
  AppBuilder/ABFactory.js
  AppBuilder/platform/ABObjectApi.js
  AppBuilder/platform/dataFields/ABFieldConnect.js
  AppBuilder/platform/views/viewComponent/ABViewDetailCustomComponent.js
  AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
  AppBuilder/platform/views/viewComponent/ABViewFormDatepickerComponent.js
  AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
Labels: patch

#498 Additional Logging Info and quick fix
  AppBuilder/platform/dataFields/ABFieldJson.js
  resources/NetworkRestSocket.js
Labels: patch

#500 Fix Unit tests
  .babelrc
  .eslintrc.js
  .github/workflows/unit-tests.yml
  AppBuilder/platform/views/viewComponent/ABViewDataFilterComponent.js
  AppBuilder/platform/views/viewComponent/ABViewDetailComponent.js
  package-lock.json
  package.json
  test/AppBuilder/platform/views/viewComponent/ABViewDetailCheckboxComponent.js.test.js
  test/AppBuilder/platform/views/viewComponent/ABViewDetailConnectComponent.js.test.js
  test/AppBuilder/platform/views/viewComponent/ABViewDetailTextComponent.test.js
  test/AppBuilder/platform/views/viewComponent/Common.test.js
  test/_mock/AB.js
  test/_setup.js
Labels: skip-release

#501 Downgrade tinymce dependency
  package-lock.json
  package.json
Labels: patch

#503 Listen to DataCollection to know if it is empty and update UI
  AppBuilder/platform/views/viewComponent/ABViewDetailComponent.js
Labels: bug, patch

#499 Fix errors where Form submissions can reset other connections
  AppBuilder/ABFactory.js
  AppBuilder/platform/dataFields/ABFieldConnect.js
  AppBuilder/platform/views/viewComponent/ABViewTabComponent.js
Labels: patch

#504 *Fix submit empty value when connect field data does not load completely
  AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
Labels: patch
