Repository CruGlobal/ab_platform_web, pull requests merged in 2024-03, with the labels that each got.

#457 +Add delete feature to the Form widget
  AppBuilder/platform/views/ABViewForm.js
  AppBuilder/platform/views/viewComponent/ABViewFormButtonComponent.js
Labels: patch

#464 *Fix populate value to the datepicker
  AppBuilder/platform/dataFields/ABField.js
  AppBuilder/platform/views/viewComponent/ABViewFormButtonComponent.js
Labels: patch

#448 Make Network Rest Great Again
  AppBuilder/platform/ABModel.js
  AppBuilder/platform/ABObject.js
  AppBuilder/platform/dataFields/ABFieldConnect.js
  AppBuilder/platform/dataFields/ABFieldUser.js
  AppBuilder/platform/views/ABViewForm.js
  AppBuilder/platform/views/viewComponent/ABViewCarouselComponent.js
  AppBuilder/platform/views/viewComponent/ABViewChartComponent.js
  AppBuilder/platform/views/viewComponent/ABViewConditionalContainerComponent.js
  AppBuilder/platform/views/viewComponent/ABViewDetailComponent.js
  AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
  AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
  AppBuilder/platform/views/viewComponent/ABViewTextComponent.js
  init/Bootstrap.js
Labels: patch

#467 +Add custom build webpack action
  .github/workflows/docker-build-custom.yml
Labels: patch

#470 Fix setting data-cy on a connected record form field
  AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
Labels: patch

#473 *Fix filter of CSV Exporter widget
  AppBuilder/platform/views/viewComponent/ABViewCSVExporterComponent.js
Labels: patch

#474 *Fix populate M:1 connect option
  AppBuilder/platform/dataFields/ABFieldConnect.js
  AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
Labels: patch

#475 Fix the clear selection UI on connected fields.
  styles/ui.css
Labels: bug, patch

#476 Fix UI displaying connected fields with "Add New" buttons when label position is "top"
  AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
Labels: bug, patch

#477 Redirect to "/auth/login" to authenticate CAS/Okta
  init/Bootstrap.js
  init/initDefinitions.js
Labels: minor

#469 Various patches made while watching our tests run
  AppBuilder/platform/ABObject.js
  AppBuilder/platform/dataFields/ABField.js
  AppBuilder/platform/dataFields/ABFieldJson.js
  AppBuilder/platform/dataFields/ABFieldUser.js
  AppBuilder/platform/views/ABViewForm.js
  AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
Labels: patch

#479 Fix spacing on connected fields labels.
  AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
Labels: patch

#481 Fix calling uid on undefined
  AppBuilder/platform/ABComponent.js
Labels: patch

#478 *Update items in the grid when mass updating
  AppBuilder/platform/views/ABViewGridPopupMassUpdate.js
Labels: patch
