Repository CruGlobal/ab_platform_web, pull requests merged in 2024-05, with the labels that each got.

#510 *Fix populate option with empty connect value
  AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
Labels: patch

#512 We need to pass forUpdate param otherwise the UUID of the connection …
  AppBuilder/platform/dataFields/ABFieldConnect.js
Labels: bug, patch

#521 *Fix this.AB is undefined
  AppBuilder/platform/views/ABViewGridPopupSortFields.js
Labels: patch

#523 *Fix use global.AB variable in E2E testing
  AppBuilder/platform/views/ABViewGridPopupSortFields.js
Labels: patch

#524 Prevent an error when UI component isn't present in DOM
  ui/ClassUIPage.js
Labels: patch

#528 Corrective datetimepicker to show by type (date,time,datetime) https:…
  AppBuilder/platform/views/viewComponent/ABViewFormDatepickerComponent.js
  js/webix/locales/th-TH.js
Labels: minor
