Repository CruGlobal/ab_platform_web, pull requests merged in 2024-01, with the labels that each got.

#422 *Fix display safe html tags in the Detail widget
  AppBuilder/platform/views/viewComponent/ABViewDetailItemComponent.js
Labels: patch

#424 Fix unhandled errors reported in Sentry
  AppBuilder/platform/FilterComplex.js
  AppBuilder/platform/views/viewComponent/ABViewMenuComponent.js
  AppBuilder/platform/views/viewComponent/ABViewTabComponent.js
  resources/NetworkRestSocket.js
Labels: patch

#421 Loading Performance Tweaks
  ABDesigner/ab_work_object_workspace_datatable.js
  ABDesigner/ab_work_object_workspace_formSidePanel.js
  ABDesigner/ab_work_object_workspace_gantt.js
  ABDesigner/ab_work_object_workspace_kanban.js
  ABDesigner/ab_work_object_workspace_popupCountColumns.js
  ABDesigner/ab_work_object_workspace_popupExport.js
  ABDesigner/ab_work_object_workspace_popupFrozenColumns.js
  ABDesigner/ab_work_object_workspace_popupHeaderEditMenu.js
  ABDesigner/ab_work_object_workspace_popupHideFields.js
  ABDesigner/ab_work_object_workspace_popupMassUpdate.js
  ABDesigner/ab_work_object_workspace_popupNewDataField.js
  ABDesigner/ab_work_object_workspace_popupSortFields.js
  ABDesigner/ab_work_object_workspace_popupSummaryColumns.js
  AppBuilder/platform/ABObject.js
  AppBuilder/platform/views/ABViewFormConnect.js
  AppBuilder/platform/workspaceViews/ABObjectWorkspaceView.js
  AppBuilder/platform/workspaceViews/ABObjectWorkspaceViewCollection.js
  AppBuilder/platform/workspaceViews/ABObjectWorkspaceViewComponent.js
  AppBuilder/platform/workspaceViews/ABObjectWorkspaceViewGantt.js
  AppBuilder/platform/workspaceViews/ABObjectWorkspaceViewGrid.js
  AppBuilder/platform/workspaceViews/ABObjectWorkspaceViewKanban.js
  styles/loader.css
  ui/loading.js
  webpack/index.ejs
Labels: patch

#427 [fix] prevent missing form item errors
  AppBuilder/platform/dataFields/ABFieldConnect.js
  AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
Labels: patch

#426 [fix] have the delete handler actually call the "delete" event.
  AppBuilder/platform/ABModel.js
Labels: patch

#429 Performance Improvements
  AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js
  init/pdfjs.js
  package-lock.json
  package.json
  styles/ui.css
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: patch

#430 Adjust lighthouse workflow for lhci server
  .github/workflows/lighthouse.yml
Labels: skip-release

#432 *Fix load PDF library files
  AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js
  init/pdfjs.js
Labels: patch

#433 *Fix the query workspace page
  AppBuilder/platform/ABObject.js
Labels: patch

#431 Defer loading formio and tinymce
  AppBuilder/platform/views/viewComponent/ABViewFormTextboxComponent.js
  AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js
  index.js
  init/Bootstrap.js
  init/formio.js
  js/webix/webixResources.js
  package-lock.json
  package.json
  ui/portal_work_inbox_accordion.js
  webix_custom_components/customComponentManager.js
  webix_custom_components/formioBuilder.js
  webix_custom_components/formioPreview.js
  webix_custom_components/lazyComponent.js
  webix_custom_components/tinyMce.js
  webpack.common.js
Labels: patch

#434 [fix] patches based upon Sentry issues
  AppBuilder/platform/dataFields/ABFieldFile.js
  AppBuilder/platform/dataFields/ABFieldImage.js
  AppBuilder/platform/dataFields/ABFieldList.js
  AppBuilder/platform/dataFields/ABFieldTree.js
  AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
  AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
  AppBuilder/platform/views/viewComponent/ABViewFormDatepickerComponent.js
  resources/NetworkRest.js
Labels: patch

#435 Performance Improvements
  index.js
  init/Bootstrap.js
  js/webix/webixResources.js
  package-lock.json
  package.json
  styles/ui.css
  ui/loading.js
  webpack.common.js
  webpack.prod.js
  webpack/index.ejs
Labels: patch

#438 include sailsio via webpack so we can minimize/compress it
  index.js
  init/sailsIo.js
  package-lock.json
  package.json
  webpack.common.js
  webpack/index.ejs
Labels: patch

#441 fix loading data into formio for inbox tasks
  webix_custom_components/formioPreview.js
Labels: patch

#445 +Add "checked" and "unchecked" filter conditions
  AppBuilder/platform/FilterComplex.js
Labels: patch

#444 *Fix disable the save button
  AppBuilder/platform/views/ABViewForm.js
  AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
Labels: patch

#443 Jh/performance preloader
  config/Config.js
  index.js
  init/Bootstrap.js
  init/initConfig.js
  init/initDefinitions.js
  init/initUser.js
  init/sailsIo.js
  package-lock.json
  package.json
  ui/portal_work_inbox.js
  webix_custom_components/formioPreview.js
  webpack.common.js
  webpack/index.ejs
Labels: skip-release

#442 Detect slow network and display a warning
  init/Bootstrap.js
  resources/Network.js
  styles/ui.css
  ui/portal_work.js
  utils/networkTest.js
  utils/performance.js
  webpack/index.ejs
Labels: minor

#446 Jh/performance
  config/Config.js
  index.js
  init/Bootstrap.js
  init/initConfig.js
  init/initDefinitions.js
  init/initUser.js
  init/sailsIo.js
  ui/portal_work_inbox.js
  webpack/index.ejs
Labels: minor

#447 [fix] ABViewFormConnect components that can select multiple values now handle encoded values "val1,val2" properly
  AppBuilder/platform/dataFields/ABFieldConnect.js
  AppBuilder/platform/dataFields/ABFieldUser.js
  AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
  AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
Labels: patch
