Repository CruGlobal/ab_platform_web, pull requests merged in 2025-07, with the labels that each got.

#660 Catching error for showing popup
  ui/portal_work_task_user_form.js
Labels: bug, patch

#663 Catching error for showing popup
  ui/portal_work_task_user_form.js
Labels: patch

#664 master -> main Update pr-merge-release.yml
  .github/workflows/pr-merge-release.yml
Labels: patch

#665 *Fix github actions
  .github/workflows/docker-build-custom.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/update-core-version.yml
Labels: patch

#667 Enable connect field on mobile
  AppBuilder/platform/dataFields/ABFieldConnect.js
Labels: minor
