Repository CruGlobal/ab_platform_web, pull requests merged in 2025-06, with the labels that each got.

#654 Add page routing by query params
  ui/portal_work.js
Labels: minor

#656 workflows use GH App Auth instead of a PAT
  .github/workflows/dispatch-web-update.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/pr-merge-release.yml
  .github/workflows/update-core-version.yml
Labels: skip-release

#658 Update organization
  .github/workflows/addissuetoproject.yml
  .github/workflows/docker-build-custom.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/lighthouse.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/pr-merge-release.yml
  .github/workflows/update-core-version.yml
  README.md
  ui/portal_work.js
Labels: skip-release

#659 Fix bug missing value
  AppBuilder/platform/process/tasks/ABProcessGatewayExclusive.js
  ui/portal_auth_login_resetRequest.js
  webix_custom_components/formioBuilder.js
Labels: bug, patch

#657 Add an API Request Service task to processes
  AppBuilder/platform/ABProcess.js
  AppBuilder/platform/process/tasks/ABProcessTaskServiceApi.js
  AppBuilder/platform/process/tasks/ABProcessTaskServiceCalculate.js
Labels: minor
